### ISSUE TITLE
`timestamp': undefined method `iso8601'

### ISSUE THREAD

**Issue by raam86** [whatthewhat/simple_segment#17]
I have this simple example:

```
require 'simple_segment'

Analytics = SimpleSegment::Client.new({
        write_key: 'MY KEY',
            on_error: Proc.new { |status, msg| print msg }
})

Analytics.track(
    anonymous_id: '019mr8mf4r',
    event: 'Item Purchased',
    properties: { revenue: 39.95, shipping: '2-day' })
```

running this results in:
``` 
/Users/rrh/.rvm/gems/ruby-2.3.1/gems/simple_segment-0.2.0/lib/simple_segment/operations/operation.rb:47:in `timestamp': undefined method `iso8601' for Time:Class (NoMethodError)
	from /Users/rrh/.rvm/gems/ruby-2.3.1/gems/simple_segment-0.2.0/lib/simple_segment/operations/operation.rb:33:in `base_payload'
	from /Users/rrh/.rvm/gems/ruby-2.3.1/gems/simple_segment-0.2.0/lib/simple_segment/operations/track.rb:12:in `build_payload'
	from /Users/rrh/.rvm/gems/ruby-2.3.1/gems/simple_segment-0.2.0/lib/simple_segment/operations/track.rb:5:in `call'
	from /Users/rrh/.rvm/gems/ruby-2.3.1/gems/simple_segment-0.2.0/lib/simple_segment/client.rb:36:in `track'
	from anal.rb:8:in `<main>'
(.dev) Raams-MacBook-Pro:ruby_anal rrh$ 
```

any advice?

**Comment by whatthewhat** [comment]
@raam86 good catch! Looks like we use [Time#iso8601](https://ruby-doc.org/stdlib-2.3.0/libdoc/time/rdoc/Time.html#method-i-iso8601) without explicitly requiring the time extensions..

I'll push a bugfix today or tomorrow, in the mean time you can do the following:

```ruby
require 'time'
require 'simple_segment'

# your code...
```
